---
format:
  revealjs:
    spotlight: true
    touch: true
    controls: true
    pointer: true
    center-title-slide: false
    transition: fade
    transition-speed: fast
    scrollable: true
    slide-number: true
    incremental: false
    multiplex: true
    chalkboard: true
    theme: [default, custom.scss]
    filters:
     - highlight-text
bibliography: references.bib
lightbox: true
csl: diagnostic-microbiology-and-infectious-disease.csl
revealjs-plugins:
  - pointer
filters:
  - highlight-text
---

## Lecture 1: Principles of Antibiotic Therapy

<br> <br>

Russell E. Lewis <br> Associate Professor of Infectious Diseases <br> Department of Molecular Medicine <br> University of Padua

<br> {{< fa solid envelope size=1x >}} russelledward.lewis\@unipd.it <br> {{< fa brands github size=1x >}} https://github.com/Russlewisbo


------------------------------------------------------------------------

## Mortality reduction with antibiotic therapy {.smaller}

<br>

| Disease                      | Pre-antibiotic | Antibiotic | Change |
|------------------------------|----------------|------------|--------|
| Community-acquired pneumonia | \~35%          | \~10%      | -25%   |
| Nosocomial pneumonia         | \~60%          | \~30%      | -30%   |
| Bacterial endocarditis       | \~100%         | \~25%      | -75%   |
| Gram-negative bacteremia     | \~70%          | \~10%      | -10%   |
| Bacterial meningitis         | \>80%          | \< 20%     | -60%   |
| Skin infection               | \~11%          | \<0.5%     | -10%   |

## Principle #1: Accurate differential diagnosis

## Principle #2: Only use antibiotics when they alter clinical course

## Principle #3: Empirically target microbes in differential diagnosis

## Principle #4: A lower threshold for empirical therapy should be used in critically-ill patients

## Principle #5: Host factors affect the spectrum of empirical therapy

## Principle #6: PK/PD principles impact optimal treatment

## Principle #7: De-escalate antibiotic therapy based on microbiology results and clinical (biomarker) responses

## Principle #8: If therapy is not working, consider source control or alternative diagnosis before broadening therapy

## Principle #9: Distiniguish new infection from failure of initial therapy

## Principle #10: The duration of therapy should be as short as possible based on available evidence (shorter is better)

## Common myths of antibiotic therapy

## Bactericidal antibiotics are more effective than bacteriostatic

## Oral therapy is less effective than IV for complex infections

## Combination therapy: *The good, the bad,...the ugly*

## Does combination therapy prevent resistance?